AppFlowy-IO/AppFlowy-Cloud

README.md, docker/postgres.Dockerfile
fix ci (building postgres) with --fix-missing flag
=> ci: trigger ci

doc/deployment.md
Clarify docker compose installation steps since it should come installed with docker desktop/engine.
Added instructions to curl the metrics endpoint of the server to verify that it is running.
=> docs: update deployment doc

src/application.rs
This PR adds some additional logging to the `init_state` function in `src/application.rs` so users get a bit more info in their logs if something else fails down the line.
fixes #207
Please let me know if I can improve this PR at all, and thanks for all your hard work on this repo! :)
=> feat: add additional info logging to init_state function in application.rs

doc/DEPLOYMENT.md, docker-compose-dev.yml, docker-compose.yml, nginx/nginx.conf
Docs and comments about optional services in docker-compose
=> feat: update optional component of deployment

docker/gotrue.Dockerfile
- Architecture agnostic for `gotrue` image build
=> feat: gotrue build arch agnostic

admin_frontend/templates/components/admin_sso_list.html, admin_frontend/templates/components/admin_top_menu_bar.html, admin_frontend/templates/components/admin_users.html, admin_frontend/templates/components/top_menu_bar.html, admin_frontend/templates/components/user_details.html, admin_frontend/templates/layouts/base.html, admin_frontend/templates/pages/login.html
make sure that all output text does not render as html element
=> feat: add escape for all template output

doc/DEPLOYMENT.md
Docker compose file for optional services is docker-compose-extra**s**.yml.
=> Fix typo in DEPLOYMENT.md

admin_frontend/src/web_api.rs, deploy.env, docker-compose.yml, libs/client-api/src/http.rs, libs/gotrue/src/api.rs, src/application.rs, src/biz/collab/access_control.rs, src/biz/collab/storage.rs, src/biz/workspace/access_control.rs, src/middleware/access_control_mw.rs
- fix self hosting env variables
=> Admin frontend/self host env

Cargo.lock, Cargo.toml, build/client_api_deps_check.sh, libs/client-api-test-util/src/test_client.rs, libs/client-api/Cargo.toml, libs/client-api/src/collab_sync/mod.rs, libs/client-api/src/collab_sync/plugin.rs, libs/client-api/src/collab_sync/sink.rs, libs/client-api/src/collab_sync/sink_config.rs, libs/client-api/src/collab_sync/sink_pending_queue.rs, libs/client-api/src/collab_sync/sync_control.rs, libs/client-api/src/ws/client.rs, libs/realtime-entity/src/collab_msg.rs, libs/realtime-protocol/src/protocol.rs, libs/realtime/src/collaborate/broadcast.rs, libs/realtime/src/collaborate/group_control.rs, libs/realtime/src/collaborate/plugin.rs, tests/collab/edit_permission.rs, tests/collab/edit_workspace.rs, tests/collab/multi_devices_edit.rs, tests/collab/single_device_edit.rs
init sync when client missing some broadcast update
=> Optimize sync

doc/DEPLOYMENT.md
improves general grammar and adds some clarity
=> docs: update DEPLOYMENT.md

libs/database/src/file/file_storage.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/file_storage.rs
- remove max file storage
- remove single file storage limit
=> feat: remove storage limit

.sqlx/query-bde2b88ffb1b59362c7ae82369892c79131c175924f95e5d48d75931fb846f41.json, libs/client-api/src/http.rs, libs/database/src/user.rs, src/api/workspace.rs, src/biz/collab/access_control.rs, src/biz/workspace/ops.rs, tests/workspace/member_crud.rs
- allow members to leave workspace
- owner are not allowed to leave workspace
=> Leave workspace

admin_frontend/src/web_api.rs, admin_frontend/templates/components/sidebar.html, admin_frontend/templates/pages/login.html, src/api/workspace.rs, src/biz/workspace/ops.rs
- Invite user will automatically send email to target user which redirects to the invite page
=> Admin frontend/email invite

admin_frontend/src/web_api.rs, admin_frontend/templates/pages/login.html
- simplify magic link login
- fix magic login not working when another user is logged in
=> Test deploy token login

Cargo.lock, Cargo.toml, libs/client-api/Cargo.toml, libs/client-api/src/ws/client.rs, libs/client-api/src/ws/msg_queue.rs, libs/collab-rt-entity/src/realtime_proto.rs, libs/collab-rt/src/rt_server.rs, src/api/ws.rs, src/application.rs, src/biz/actix_ws/client/rt_client.rs, src/biz/actix_ws/server/rt_actor.rs, src/biz/pg_listener.rs, tests/websocket/actor_test.rs, tests/websocket/mod.rs
1. **Support Writing Tests for Client/Server:** Introduce ways to easily test the interaction between clients and servers without needing a real network
2. **Remove Retry Sending Client Message:** Stop trying to resend messages from the client to the server
3. **Remove Unnecessary Dependencies:** Get rid of extra code or libraries that aren't needed anymore, especially those related to user management
=> refactor: actix-ws 

.sqlx/query-374c2d7b26f923328edd09b0d515d59426119615a8d5d8a46101f6ccec00d617.json, Dockerfile, libs/database/src/workspace.rs, src/api/workspace.rs, src/biz/workspace/ops.rs, tests/workspace/member_crud.rs
- add ca-certs for mailer
- check if user already exists
- check if there is already pending invitation
=> feat: improve email workspace invitations

Cargo.lock, Cargo.toml, libs/client-api-test-util/Cargo.toml, libs/client-api-test-util/src/test_client.rs, libs/client-api/Cargo.toml, libs/collab-rt-entity/Cargo.toml, libs/collab-rt-protocol/Cargo.toml, libs/collab-rt-protocol/src/protocol.rs, libs/database-entity/Cargo.toml, libs/database/Cargo.toml, libs/shared-entity/Cargo.toml, libs/workspace-template/Cargo.toml, libs/workspace-template/src/hierarchy_builder.rs, services/appflowy-collaborate/Cargo.toml, services/appflowy-collaborate/src/group/broadcast.rs
Related to https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/216
This PR upgrades yrs dependencies together with AppFlowy-Collab. It brings a bunch of bug fixes and should help with issues we have on a collab server.
=> Update Yrs and AppFlowy-Collab

Cargo.lock, libs/collab-stream/Cargo.toml, libs/collab-stream/src/client.rs, libs/collab-stream/src/stream_group.rs, services/appflowy-history/src/core/manager.rs
1. add max len for redis stream
2. set expiration time for redis stream
=> chore: optimize redis stream space usage

src/api/search.rs
Even though last merged PR passed all checks #584, after merging the main became broken: https://github.com/AppFlowy-IO/AppFlowy-Cloud/actions/runs/9282497417/job/25540649242 .
=> chore: fix after merge compilation issues

nginx/nginx.conf
dynamic service resolution for appflowy cloud ai service. prevents nginx in a crash loop when ai service in not available
=> fix: nginx optional resolution for ai service

libs/collab-stream/src/stream_group.rs, services/appflowy-collaborate/src/collab/queue.rs, services/appflowy-collaborate/src/collab/queue_redis_ops.rs, services/appflowy-indexer/src/collab_handle.rs, services/appflowy-indexer/src/consumer.rs, services/appflowy-indexer/src/extract.rs, services/appflowy-indexer/src/watchers/document_watcher.rs
This PR fixes ongoing issues with appflowy-indexer not updating the embeddings after some updates have been made.
This was related to following issue - apparently `document_data.text_map` stores all of the text fields, however not all of them are reachable from document root page down through blocks tree. Atm. more reliable source is to use `document_data.blocks[id].data.delta`.
**This is to solve current issue at hand. The actual issue that needs to be solved is the fact, that text data is stored in two places**: as delta in blocks and in text_map. In practice this may lead to issues in the futures (starting from memory issues since deltas are part of the `yrs::Doc`). If we need deltas we can generate them at any time from YText elements.
Below example for reference.
```rust
DocumentData …
```
=> fix: index all of the document blocks

migrations/20240617135926_af_workspace_foreign_key_indices.sql
- Speed up database by adding foreign key for `af_workspace` table
- creating and deleting workspace
- user initialization
=> chore: add foreign key indices for workspace table

Cargo.lock, libs/appflowy-ai-client/src/client.rs, libs/appflowy-ai-client/src/dto.rs, libs/appflowy-ai-client/tests/chat_test/completion_test.rs, libs/appflowy-ai-client/tests/chat_test/qa_test.rs, libs/appflowy-ai-client/tests/row_test/summarize_test.rs, libs/appflowy-ai-client/tests/row_test/translate_test.rs, libs/client-api/src/http.rs, libs/database-entity/Cargo.toml, libs/database-entity/src/dto.rs, src/api/ai.rs, src/api/chat.rs, src/api/util.rs, src/biz/chat/ops.rs, tests/ai_test/complete_text.rs
Support switching ai model:
```rust
pub enum AIModel {
#[default]
GPT35 = 0,
GPT4o = 1,
Claude3Sonnet = 2,
Claude3Opus = 3,
Local = 4,
}
```
=> feat: support switch model

migrations/20240626184736_publish_collab_4.sql
- add index for faster query
- add uniqueness for data integrity
=> feat: add index and uniqueness for publish name

services/appflowy-collaborate/src/collab/queue_redis_ops.rs, services/appflowy-collaborate/src/config.rs, src/biz/search/ops.rs, src/config/config.rs
Shorten the write interval time for open collab
=> chore: shorten default write interval

Cargo.lock, services/appflowy-collaborate/Cargo.toml, services/appflowy-collaborate/src/config.rs, services/appflowy-collaborate/src/lib.rs, services/appflowy-collaborate/src/main.rs, services/appflowy-collaborate/src/telemetry.rs
Add telemetry to the appflowy collaborate service.
=> feat: add telemetry to appflowy collaborate service

libs/app-error/src/lib.rs, src/api/ai.rs, src/api/chat.rs
Return AI service unavailable error when streaming
=> fix: return ai stream error when service unavailable

.sqlx/query-f1c55a5255b1c7e5c96e21cb8557b6d46f713630d819f94cc7a966dbdaf00a2a.json, Cargo.lock, libs/client-api-test/src/client.rs, libs/client-api-test/src/test_client.rs, libs/client-api/src/http.rs, libs/database-entity/src/dto.rs, libs/database/src/pg_row.rs, libs/database/src/workspace.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/workspace/ops.rs, tests/file_test/put_and_get.rs, tests/gotrue/admin.rs, tests/user/delete.rs, tests/user/sign_in.rs, tests/workspace/invitation_crud.rs, tests/workspace/member_crud.rs, tests/workspace/publish.rs, tests/workspace/workspace_crud.rs, tests/workspace/workspace_settings.rs
- deprecate the user of `AFWorkspace`, just use `Vec<AFWorkspace>`
- add option to include `member_count` for each workspace when fetching workspace
=> feat: improve workspace api

libs/client-api/src/http.rs
there are invalid version number passed into server. Adding constraint for app version number.
=> chore: enforce client version

libs/shared-entity/src/dto/billing_dto.rs
- add return information for single file upload limits for user
=> chore: add single upload limit

libs/client-api/src/http_billing.rs, libs/shared-entity/src/dto/billing_dto.rs
- add client api http request for subscription trial
- use struct to represent subscription link request
=> Create sub params

services/appflowy-collaborate/src/group/state.rs, services/appflowy-collaborate/src/metrics.rs
New metrics to track the number of users who are currently editing collab.
=> feat: add metrics for number of editing users

libs/client-api/src/collab_sync/collab_sink.rs, libs/client-api/src/collab_sync/collab_stream.rs, libs/collab-rt-entity/src/server_message.rs
when receve server miss update, remove all pending message.
=> fix: invalid message id

deploy.env, dev.env, libs/appflowy-ai-client/src/client.rs, services/appflowy-collaborate/src/group/group_init.rs, services/appflowy-collaborate/src/group/state.rs, services/appflowy-collaborate/src/indexer/provider.rs, services/appflowy-collaborate/src/rt_server.rs, src/telemetry.rs
1. set timeout when sending chat requestion
2. using env to enable/disable document indexer
=> chore: set chat request timeout

libs/workspace-template/assets/mobile_guide.json, libs/workspace-template/src/document/getting_started.rs, tests/workspace/default_user_workspace.rs
=> chore: update getting_started icon and remove empty paragraph

.dockerignore, .sqlx/query-785c4c1e9b393a1f04a88136211df0c5daa7ad0c52f3e7e071156595262ca44f.json, .sqlx/query-ee58ab18f882ed89f3506d3e28eef43c32e09e6c545a08f35fb5169e84553af6.json, libs/app-error/src/lib.rs, libs/database/src/publish.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/collab/folder_view.rs, src/biz/collab/mod.rs, src/biz/collab/ops.rs, src/biz/collab/publish_outline.rs, src/biz/workspace/publish_dup.rs
Add endpoint to support published view outline. Any view, which is either published, or has any direct or indirect descendant  that is published, will need to be displayed. All view that are space will need to be displayed
=> feat: published view outline endpoint

libs/shared-entity/src/dto/workspace_dto.rs, src/biz/collab/publish_outline.rs
Add is_published field to publish outline response.
=> feat: add is published field to published outline response

src/biz/collab/publish_outline.rs
There''s currently a bug, in which the folder data structure might not be entirely correct. Specifically, the parent view id of a child might not necessary match that of the parent. We will mitigate this issue by filtering out such case in the publish outline endpoint.
=> fix: filter out children which the view's parent does not match the actual parent view id

admin_frontend/src/config.rs
Follow up to https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/792
=> chore: fix formating and add descriptive error message for parse failures

Cargo.lock, libs/database-entity/Cargo.toml, libs/database-entity/src/dto.rs, libs/database-entity/src/error.rs, libs/database-entity/src/lib.rs, script/client_api_deps_check.sh
Add methods to support conversion from CollabParams to protobuf serialized format and vice versa
=> feat: support protobuf serialization and deserialization for CollabParams

src/application.rs
Fixes admin re-initialization due after using latest gotrue image.
Resolves https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/865
=> fix: admin initialization

services/appflowy-collaborate/src/command.rs
Limit the number of concurrency when fetching encoded collab in batch.
=> fix: limit concurrency level of batch get encode collab

.github/workflows/integration_test.yml
Postgres password was parameterized in https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/901 , and the default password has been modified from `password` to `changepassword` . Github CI action needs to be updated accordingly.
=> fix: integration test failure due to password mismatch

dev.env, docker-compose-ci.yml, docker-compose-dev.yml, migrations/before/supabase_auth.sh
1. Update docker compose dev and docker compose env based on https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/918
2. Remove the need of `anon` , `authenticated` and `supabase_admin` role.
=> fix: remove dependencies on unnecessary postgres roles

services/appflowy-history/src/config.rs, services/appflowy-worker/src/config.rs, src/config/config.rs
Fix https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/907 .
=> fix: masked postgres password in logs

libs/database-entity/src/dto.rs, src/biz/template/ops.rs, tests/workspace/template.rs
Add publish info for the templates return by template home page.
=> feat: add publish info to template home page

.sqlx/query-fffe6f01abf0e5d8649a49b5793ccb92a9f823f07c363341357ea74bf4f4a16d.json, libs/client-api/src/http_publish.rs, libs/database/src/publish.rs, src/api/workspace.rs, src/biz/workspace/ops.rs, src/biz/workspace/publish.rs, tests/workspace/publish.rs
- Add http api for removing default view id for a workspace
=> feat: delete default view for workspace

deploy.env, docker-compose-ci.yml, docker-compose-dev.yml, docker-compose.yml, migrations/before/supabase_auth.sh
=> refactor: remove supabase username variable and force set to "supabase_auth_admin"

Cargo.lock, Cargo.toml, libs/workspace-template/src/hierarchy_builder.rs, src/biz/workspace/page_view.rs, src/biz/workspace/publish_dup.rs, tests/workspace/publish.rs
=> chore: Upgrade the collab library to fix the issue with importing Notion zip files that contain embedded zip attachments.

docker-compose.yml
Fixing gotrue service context to correctly handle volume copies and Dockerfile path.
=> bugfix(issue-969): docker compose gotrue service with right context

libs/client-api/src/http_view.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/collab/folder_view.rs, src/biz/workspace/page_view.rs, src/biz/workspace/publish_dup.rs, tests/workspace/page_view.rs
This PR add API to update page icon, name, and extra. Frontend application is expected to supply None for icon if the intention is to remove the icon, and some string values otherwise.
=> feat: API for updating page icon, name, and extra

libs/client-api/src/http_view.rs, src/api/workspace.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
API for restoring page from trash.
=> feat: api for restore page from trash

.github/workflows/integration_test.yml, src/api/workspace.rs
- add `admin_frontend` to test matrix for more consistent tests
=> chore: add admin frontend to test matrix

libs/database/src/workspace.rs, src/biz/user/user_init.rs, src/biz/user/user_verify.rs, src/biz/workspace/ops.rs
- Use batch insertion when initializing collabs for a workspace
=> feat: use batch insert collab for workspace creation

admin_frontend/src/web_api.rs
=> fix: use htmx redirect instead

libs/client-api/src/http_view.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/collab/folder_view.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
API endpoint for creating new space from appflowy web.
=> feat: api for create space

libs/access-control/src/casbin/adapter.rs
Currently, we are loading collab policies, even though our access control model doesn't currently rely on it. As one collab policies is added per collab, it took more computational resources for casbin to enforce a policy when the number of collab is huge.
=> fix: stop loading collab policies to improve access control evaluation

libs/client-api/src/http_view.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
=> feat: api to update space

Cargo.lock, Cargo.toml, libs/database/src/collab/collab_storage.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/biz/collab/ops.rs, src/biz/workspace/ops.rs, src/biz/workspace/page_view.rs, src/biz/workspace/publish_dup.rs, tests/workspace/page_view.rs, tests/workspace/publish.rs
Support creating new page in appflowy web for grid, board and calendar.
=> feat: add support for create database pages via API

src/biz/workspace/page_view.rs
The database fields are wrongly set to true for every fields.
=> fix: primary field should be unique for new database page

src/api/file_storage.rs
Using `try_reserve_exact` to allocate memory for upload file content
=> chore: safe allocate mem 

.github/workflows/integration_test.yml, .github/workflows/stress_test.yml, Cargo.lock, deploy.env, docker-compose-stress-test.yml, tests/collab/stress_test.rs, xtask/Cargo.toml, xtask/src/main.rs
run test that start with `stress_test` on self-hosted runner
=> chore: enable running stress on on self-hosted runner

libs/client-api/src/http_view.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
=> feat: api for moving page

services/appflowy-collaborate/src/indexer/provider.rs
This PR adds two logs (at `info` level) to tell us how many unindexed collabs were discovered after restart, and when the process finishes and how long did it took.
=> chore: add logging for reindexing docs after restart

deploy.env, dev.env, libs/mailer/src/config.rs, libs/mailer/src/sender.rs, services/appflowy-worker/src/application.rs, services/appflowy-worker/src/config.rs, services/appflowy-worker/src/mailer.rs, src/application.rs, src/config/config.rs
- `none`
- `wrapper` (default)
- `required`
- `opportunistic`
=> feat: add option for tls mailer

deploy.env, doc/DEPLOYMENT.md
Update the self hosting documentation to include additional FAQs.
=> chore: update self hosting documentation

services/appflowy-collaborate/src/config.rs
Update AI env:
APPFLOWY_AI_SERVER_PORT -> AI_SERVER_PORT
APPFLOWY_AI_SERVER_HOST -> AI_SERVER_HOST
APPFLOWY_AI_REDIS_URL -> AI_REDIS_URL
APPFLOWY_AI_DATABASE_URL -> AI_DATABASE_URL
some envs were modified in #1133
=> chore: update env

doc/DEPLOYMENT.md, nginx/nginx.conf
Fix the current nginx conf to properly allow localhost:3000 to access /api endpoint.
=> fix: nginx conf to allow localhost:3000 to access api endpoint

.github/workflows/web_docker.yml
Modify the workflow to build arm images as well as amd images.
=> chore: add workflow to build arm appflowy web image

doc/DEPLOYMENT.md, doc/GUIDE.md, docker-compose.yml, nginx/nginx.conf
Add appflowy web as part of the docker compose setup.
=> feat: add appflowy web to docker compose

libs/client-api-test/src/user.rs
The CI test is currently failing on main branch due to changes to gotrue admin client initialization. This PR will revert the changes.
=> chore: fix CI test failure due to PR #1215

src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
Page creation API is updated to support AI Chat as well
=> feat: support chat page creation

Cargo.lock, Cargo.toml, libs/shared-entity/src/dto/workspace_dto.rs, libs/workspace-template/src/hierarchy_builder.rs, src/api/workspace.rs, src/biz/collab/folder_view.rs, src/biz/workspace/page_view.rs, src/biz/workspace/publish_dup.rs, tests/workspace/page_view.rs
Support the lock page functionality
=> feat: support lock page

Cargo.lock, Cargo.toml, libs/app-error/src/lib.rs, libs/shared-entity/src/dto/workspace_dto.rs, libs/workspace-template/src/document/mod.rs, libs/workspace-template/src/document/parser.rs, src/api/workspace.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
Allow creation of page with initial data.
=> feat: create page with initial data

libs/app-error/src/lib.rs, src/api/workspace.rs
Better error message to debug issues related to failure to get member profile.
=> chore: add better error message for get member failure

.sqlx/query-ee059aca8fba787658ad095f44bd0075aef1abc6eb0f34d11905765da9fd38e5.json, libs/database/src/workspace.rs, src/api/workspace.rs, src/biz/workspace/ops.rs
Endpoint to get workspace member via uuid
=> feat: fetch workspace member via uuid

libs/database/src/workspace.rs, migrations/20250305082545_workspace_delete_trigger.sql, src/biz/user/user_delete.rs
Trigger a notification when a user deletes a workspace or their account.
=> Workspace table notification

libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/collab/folder_view.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
Add parent view id to folder API.
=> feat: add parent view id to folder view

libs/shared-entity/src/dto/workspace_dto.rs, src/biz/collab/folder_view.rs
Add is pinned to favorite list.
=> feat: add is pinned to favorite list

libs/client-api/src/http_view.rs, libs/shared-entity/src/dto/workspace_dto.rs, src/api/workspace.rs, src/biz/workspace/page_view.rs, tests/workspace/page_view.rs
Add API for adding recent pages.
=> feat: api for add recent pages

libs/access-control/src/casbin/workspace.rs, libs/access-control/src/noops/workspace.rs, libs/access-control/src/workspace.rs, services/appflowy-collaborate/src/collab/access_control.rs, src/api/file_storage.rs, src/api/search.rs, src/api/workspace.rs, src/biz/access_request/ops.rs
Use uuid for workspace access control.
=> chore: use uuid for workspace access control

libs/shared-entity/src/dto/workspace_dto.rs, src/biz/collab/folder_view.rs, src/biz/workspace/page_view.rs
Add previous view id for individual views in  get workspace folder response.
=> feat: add prev view id for get workspace folder response

assets/mailer_templates/build_production/recovery.html, email_template/src/templates/recovery.html
Add email template for password recovery.
=> feat: add email template for password recovery

libs/client-api/src/http_guest.rs, libs/shared-entity/src/dto/guest_dto.rs, src/api/guest.rs
Ancestor id array cannot be passed as query parameter using reqwest
=> feat: use post for shared view details

libs/collab-stream/src/client.rs
This fix was possible thanks to courtesy of Jaeook Ryu. When reading collab did from redis stream, we used invalid conversion method (`String`), since when writing we write "old" as `Uuid`: https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/28173734428d5c80f574282fe45f83b831a04bdd/libs/collab-stream/src/model.rs#L489-L502
=> chore: fix collab update redis stream oid conversion
