AppFlowy-IO/AppFlowy-Cloud

build/run_local_server.sh

It might fail if you immediately run the sqlx command after `docker-compose up`

fix: run_local_server script

---

dev.env
docker-compose-dev.yml
docker-compose.yml

Use cloudflare tunnel to protect Appflowy Cloud so that the server does not need to expose the port to avoid port scanning
1. CloudFlare zero trust setting create a tunnel
2. Get tunnel token
3. put token to env
```bash
CLOUDFLARE_TUNNEL_TOKEN=eyJhIjoiOWRiODVlM2Nm...
```
4. start services
```bash
docker compose up -d 
```
5. Setting cloudflare tunnel public host

feat: Add cloudflare tunnel

---

docker-compose.yml

[Bug] tunnel service container name already in use
**Describe the bug**
tunnel service container name already in use, it will let tunnel service can't up.
**Screenshots**

fix: remove tunnel service container name

---

README.md

The `docs/DEPLOYMENT.md` is all caps now, so the link in the root README.md didn't work. This PR updates that to point to the new file name.

Update README.md - fix link to deployment guide

---

migrations/20231130150000_user_id_foreign_key.sql

fixes #187 
- Reverts the last migration as the foreign key delete cacade approach is simpler and more straight-forward.

fix: use foreign key cascade delete for user cleanup

---

docker-compose.yml

Thanks to https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/204#issuecomment-1851285350 I was able to test using these env vars and Appflowy-Cloud is able to initialize it's app state using the minio bucket I specified.
This PR updates those environment variables in the docker-compose.yml file to help others.

fix: update the S3 env vars in docker-compose.yml to not have `AWS` in them

---

Cargo.lock
Cargo.toml

This PR turns on the necessary features for rust-s3 to allow for s3 endpoints that are secured with TLS (which is still known as SSL in about half the places on the internet 😁). I also ran `cargo update rust-s3`.
- Fixes #204
I followed the advice here: https://github.com/durch/rust-s3/issues/291#issuecomment-1254116809 Here's my test notes: https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/204#issuecomment-1853688371
I've also left some [suggestions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) below to clean up some old comments.

fix: turn on ssl features for rust-s3 in Cargo.toml

---

deploy.env
dev.env
src/application.rs
src/config/config.rs

This PR allows to use custom S3 providers apart from minio that require a correctly set region, e.g. [garage](https://garagehq.deuxfleurs.fr/) (designed for self-hosting, uses far less RAM than minio, also written in Rust)

feat: S3 compatiblity with garage

---

doc/DEPLOYMENT.md

I find it unintuitive that the deployment guide for AppFlowy Cloud suggests using AMZ EC2 or Microsoft Azure VMs, which are paid services that are hosted at Amazon / Microsoft data servers. I get that the point is that the server needs to be available / reliable and those cloud compute services are. But aren't we targeting people who want to use free opensource software here?

Update DEPLOYMENT.md / Hardware Requirements

---

docker-compose.yml

This change allows for following variables found in lines 94 and 95 of DEPLOYMENT.MD .env example and lines 58 and 59 of deploy.env - Without this change, deployment easily deploys with default user/pass of minioadmin/minioadmin

Update minio root user & pass variable to match DEPLOYMENT.MD & deploy.env

---

src/main.rs

The environmental variable is loaded after the configuration has been initialized. As a result, some configuration will always use the default configuration value and not the override value in the env file, such as APPFLOWY_GOTRUE_BASE_URL.

fix: env variable load sequence

---

Cargo.lock
Cargo.toml
libs/collab-rt/Cargo.toml
libs/collab-rt/src/group/group_init.rs
libs/collab-rt/src/group/persistence.rs
libs/collab-rt/src/group/plugin/history_plugin.rs
libs/database/src/collab/collab_db_ops.rs
libs/database/src/collab/collab_storage.rs
src/api/workspace.rs
src/application.rs
src/biz/collab/cache.rs
src/biz/collab/disk_cache.rs
src/biz/collab/metrics.rs
src/biz/collab/mod.rs
src/biz/collab/ops.rs
src/biz/collab/queue.rs
src/biz/collab/queue_redis_ops.rs
src/biz/collab/storage.rs
tests/collab/collab_curd_test.rs
tests/collab/data_write_test.rs
tests/collab/mod.rs
tests/collab/multi_devices_edit.rs
tests/collab/pending_write_test.rs
tests/collab/storage_test.rs
tests/collab/util.rs
tests/sql_test/mod.rs
tests/sql_test/util.rs

Spawns a background task that periodically writes cached collaboration data to disk in a single transaction. It consolidates multiple write operations into one transaction with the goal of minimizing database transaction pool usage,
thereby enhancing performance and reducing resource contention.

feat: using transaction to write multiple records

---

Cargo.lock
Cargo.toml
libs/app-error/Cargo.toml
libs/database/Cargo.toml
libs/shared-entity/Cargo.toml
src/application.rs
tests/workspace/blob/mod.rs

The audit test is currently failing due to RUSTSEC-2024-0336. This can be patched by updating rust-s3 to 0.34.0 release candidate.

chore: patch for RUSTSEC-2024-0336

---

libs/collab-rt-protocol/src/protocol.rs
services/appflowy-collaborate/src/group/protocol.rs

This would allow us to attach internal document state to errors, that cause panics during applying CRDT state updates.
I suspect that the reason behind these panics was fixed in https://github.com/y-crdt/y-crdt/pull/405 but we won't be able to confirm that until we upgrade to the latest version or get the log data.

feat: add more detailed logging around errors in Transaction::try_encode_state_as_update_v1

---

tests/collab/single_device_edit.rs

The test, `simulate_50_offline_user_connect_and_then_sync_document_test` , currently passed even though one or more task failed due to sync failures. Added a check to make sure that all the task completed successfully.

fix: make sure test for offline user connect then sync failed when one or more future task failed

---

libs/database/src/lib.rs
libs/database/src/listener.rs
services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/lib.rs
services/appflowy-collaborate/src/pg_listener.rs
src/biz/user/user_verify.rs

Changes:
- PostgresDBListener is moved to database crate so that the listeners can be shared between different services.
- Add PgListeners to Collab service.  As of now, the PgListener implementation is not extracted to a common crate, nor does the Appflowy API service import the implementation from the Collab Service. That is due to the possibility that the listener implementation for the main API service might eventually diverge from the implementation for the collab service.

feat: add postgres listeners for collab service

---

libs/database/src/index/collab_embeddings_ops.rs
libs/database/src/index/search_ops.rs
migrations/20240529054858_workspace_add_token_usage.sql
services/appflowy-indexer/src/collab_handle.rs
services/appflowy-indexer/src/error.rs
services/appflowy-indexer/src/indexer.rs
src/biz/search/ops.rs

This PR introduces two new columns to `af_workspace` called `search_token_usage` and `index_token_usage` which are used to track spending of OpenAI tokens for both indexing and searching purposes at the workspace level.
This PR doesn't introduce any kind of workspace token limit control, it's just about tracking.

Workspace token usage

---

src/api/metrics.rs
src/api/search.rs
src/biz/search/ops.rs

This PR registers a new `search_tokens_used` counter in prometheus so that we can track how many OpenAI API tokens are used over time.

let prometheus track open ai tokens used on search

---

libs/client-api/src/http_billing.rs
services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-collaborate/src/group/cmd.rs
services/appflowy-collaborate/src/rt_server.rs

This PR fixed the errors reported by running Clippy, which includes:
- unused struct fields
- reference that is immediately dereferenced by the compiler
For some reason, the same errors wasn't reported by the same linter test on github action.

chore: fix clippy linting errors and warnings

---

services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/rt_server.rs
src/application.rs
src/config/config.rs

The following parameter values are currently hard coded:
- Maximum allowable edit count and duration
- Interval for persisting in-memory collab group to cache/disk
Allowing the above parameters to be configured will allow us to control how frequent the in-memory edit states are saved to the cache.

chore: allow collab persistence and edit state behaviour to be configurable

---

services/appflowy-collaborate/Dockerfile

Add dockerfile for collab service. This is meant for testing locally at the moment, the pipeline should be updated to release this image at a later stage when the independent collab service is production ready.

feat: dockerfile for collab service

---

services/appflowy-indexer/src/collab_handle.rs
services/appflowy-indexer/src/watchers/document_watcher.rs

This PR fixes the issue when some open-collab events can have invalid initial document state: usually document state eventually becomes valid because of subsequent updates, so we just log the warning and wait for the document to become complete.

chore: appflowy indexer - do not break the document handler on missing data

---

services/appflowy-collaborate/src/group/persistence.rs
src/api/workspace.rs

1. Using transaction when inserting list of collabs. 
2. Remove necessary sleep when trying to save data to disk since `attempt_save` will determine to save data to disk or not

chore: update create collab list api endpoint

---

migrations/20240627525836_publish_collab_5.sql

- remove existing publish name as unqiue constraint as it's possible that 2 doc have the same name different workspace with different publish_namespace.
- added unique constraint on (workspace_id, publish_name) as it is not possible(must not) that workspace contains 2 published doc having same publish_name

fix: use two column as unique constraint

---

.sqlx/query-e5d51236e5c96ac91c70cd1d1b603f63e80e4f05a45a0790dd0bde892429ef14.json
libs/database/src/workspace.rs

1. turning off `workspace.settings.disable_search_indexing` should prune `af_collab_embeddings` for that workspace: otherwise they will be outdated (as are no longer indexed) but will still appear in search results.
2. should turning on `workspace.settings.disable_search_indexing` cause all of the collabs in that workspace to be reindexed? (question to @appflowy). IMO this could be an issue: if user starts flipping the disable indexing switch, they may overburden server with redundant requests and our AI billing will grow very easily.

chore: disabling indexing on workspace prunes collab embeddings

---

migrations/20240630010030_workspace_member_foreign_key.sql

This is needed so that when a user is deleted, it is not in the workspace member table

chore: add missing foreign key

---

Cargo.lock
Cargo.toml

Related: 
- https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/230
- https://github.com/AppFlowy-IO/AppFlowy/pull/5751

chore: bump yrs to 0.19.2

---

.sqlx/query-ba86638be27dfdf52e157e07e3e22ccb5547a7815b8313b241b8b535a83e6ff1.json
libs/database/src/workspace.rs
src/biz/workspace/ops.rs
tests/workspace/publish.rs

Order comments from the latest to the oldest, instead of relying on frontend to sort the result.

fix: order comments by recency

---

.sqlx/query-e9e22adc5a6f6daf354dc122cadab41b7cc13e0d956b3204d22f26a47ad594e3.json
libs/authentication/src/jwt.rs
libs/client-api/src/http.rs
libs/client-api/src/http_publish.rs
libs/database-entity/src/dto.rs
libs/database/src/workspace.rs
src/api/workspace.rs
src/biz/workspace/ops.rs
tests/workspace/publish.rs

Handle the logic on whether a comment can be deleted by the user who request to see all the comments. This allows the frontend to enable or disable deletion action.

feat: add can be deleted field to GlobalComment

---

libs/app-error/src/lib.rs
src/biz/workspace/ops.rs
tests/workspace/publish.rs

Currently, there is no limits on the size of the comment that a user can create. This can lead to potential denial of service attack from the user, by creating excessively long comment.
To protect against such scenario, the length of the comment string is limit to 5000. The size of the string is used as opposed to the number of characters of the string, because counting the characters is an O(n) operation.

feat: impose character limits on comment

---

admin_frontend/Dockerfile

There are a few issues that leads to admin frontend image building failures:
1. admin frontend doesn't actually need appflowy collab. However, because the cargo file for admin frontend and the parent cargo toml is in the search path (refer: https://doc.rust-lang.org/cargo/reference/config.html) , the cargo config got merged and admin frontend pulls in AppFlowy Collab as well, even when it is not needed.
2. We recently introduced protobuf dependencies in AppFlowyCollab. In order to prevent compilation failure due to absence of protobuf compiler, we try to catch the panic (https://github.com/AppFlowy-IO/AppFlowy-Collab/blob/main/collab-entity/build.rs#L20) and use vendored protobuf compiler crate as fallback. We are using panic instead of Result, because in the absence of protobuf compiler, …

fix: admin front end image building failure

---

Cargo.lock
Cargo.toml
libs/app-error/Cargo.toml
libs/app-error/src/lib.rs
libs/database/Cargo.toml
libs/database/src/chat/chat_ops.rs
libs/database/src/user.rs

Update sqlx to 0.8. The new version resolve https://github.com/launchbadge/sqlx/issues/2242 , which allows gives us greater flexibility for SQL type <-> Rust struct conversion.
pgvector is also updated to 0.4 , as 0.3.x does not work for sqlx 0.8.

chore: update sqlx to 0.8

---

libs/collab-stream/src/model.rs
libs/collab-stream/src/pubsub.rs

As we already update the decoding method to handle both bincode and protobuf serialization, it is now safe to replace the bincode with protobuf serialization for collab stream.
We will proceed with removing bincode deserialization entirely for collab stream in a future version.

chore: replace bincode serialization with protobuf for collab stream

---

Cargo.lock
Cargo.toml
libs/client-api/src/collab_sync/plugin.rs
libs/client-api/src/collab_sync/sync_control.rs
libs/collab-rt-entity/src/realtime_proto.rs
libs/collab-rt-protocol/src/protocol.rs
services/appflowy-collaborate/src/group/broadcast.rs
tests/collab/missing_update_test.rs

Companion PR to https://github.com/AppFlowy-IO/AppFlowy-Collab/pull/250 - it updates client-api to no longer require or use last sync at (which was not used anyway but was passed as a method argument).

Remove last sync at

---

Cargo.lock
Cargo.toml
libs/client-api/src/collab_sync/sync_control.rs
services/appflowy-collaborate/src/collab/storage.rs
services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/group/plugin/history_plugin.rs
services/appflowy-collaborate/src/group/plugin/mod.rs
services/appflowy-collaborate/src/snapshot/snapshot_control.rs

1. Do not trigger write before server receive sync step2 from client.
2. Upgrade appflowy collab that remove undo redo in `Document` by default
3. Deprecated history plugin

chore: write collab to disk after first sync step2

---

Cargo.lock
Cargo.toml
libs/app-error/src/lib.rs
libs/database-entity/src/dto.rs
libs/database/src/file/file_storage.rs
libs/database/src/file/s3_client_impl.rs
src/api/template.rs
src/application.rs
src/biz/template/ops.rs
src/state.rs
tests/file_test/multiple_part_test.rs

Changes:
1. Add end point for supporting template center avatar upload
2. The bucket client was assuming that the object keys are always inferred from workspace id. As a result, it's hard to use the client for objects which is not associated with a workspace, such as avatar. This has been modified such that the callers of the trait are responsible for constructing the correct object key.
3. Instead of storing the content type via a separate metadata object, the content type was specified while uploading the blob to s3.

feat: endpoint for avatar upload

---

services/appflowy-collaborate/src/indexer/provider.rs
services/appflowy-collaborate/src/rt_server.rs

spawn indexer using tokio::spawn instead of spawn_locak.

chore: spawn indexer

---

services/appflowy-collaborate/src/group/cmd.rs
services/appflowy-collaborate/src/group/group_init.rs

drop/disconnect the collaboration group if there are no active editing sessions and the group's lifetime has exceeded the maximum allowed duration.

chore: drop group with maximum timeout

---

services/appflowy-collaborate/src/api.rs
services/appflowy-collaborate/src/config.rs
src/api/ws.rs
src/config/config.rs

This PR adds minimal client version verification when establishing WS connection. It's configurable via `APPFLOWY_WEBSOCKET_CLIENT_MIN_VERSION` env var (defaults to `0.5.0`).

add minimum client version validation in websocket connection establishment

---

services/appflowy-collaborate/src/rt_server.rs

Create a custom Tokio runtime for running group collaboration. Different groups may spawn on different threads, enabling concurrency. 
In Actix-Web, if a single-threaded Tokio runtime is used (e.g., via the current_thread runtime), all tokio::spawn calls will run on that single thread, meaning tasks are not distributed across multiple threads by default. However, using a multi-threaded Tokio runtime (the default configuration for Tokio) would allow tokio::spawn calls to run on multiple threads.

chore: enable multiple threads

---

libs/client-api-test/src/test_client.rs
libs/client-api/src/collab_sync/collab_stream.rs
libs/client-api/src/collab_sync/plugin.rs
libs/client-api/src/collab_sync/sync_control.rs
services/appflowy-collaborate/src/group/protocol.rs
tests/collab/missing_update_test.rs

This PR extends SyncPlugin with optional parameter, that will periodically send `SyncStep1` to the server. This way we can get notified about missing updates from other clients.
Example scenario that it solves:
1. Client 1 (C1) syncs an update to the Server
2. For whatever reason Client 2 (C2) didn't got C1 update.
3. Until C1 will send another update or C2 will restart the connection, C2 will  never get that missing update.
With this PR we can occasionally ask server to about all missing updates given our own state vector.

chore: enable setting up periodic sync step 1 sends from sync plugin

---

libs/client-api/src/collab_sync/sync_control.rs
libs/collab-rt-protocol/src/message.rs
libs/collab-rt-protocol/src/protocol.rs
services/appflowy-collaborate/src/group/protocol.rs

1. client initiates a sync process.
2. server responds with sync step 2.
3. client applies the update from sync step 2 but return a "client missing update" error. As a result, the server never receives the updates from the client.
This PR return current `txn` state vector when missing update. Client will calculate missing updates for this state vector

chore: try to fix inifinite sync

---

libs/collab-rt-entity/src/realtime_proto.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/indexer/document_indexer.rs
services/appflowy-collaborate/src/indexer/provider.rs
src/api/workspace.rs

This PR modified document indexer to enable reusing `Arc<RwLock<Collab>>` supplied by persistence group instead of recreating it every time when `save` is being called. This means that we need to hold a lock a little bit longer (because we need to get Document text data), but we don't waste CPU/memory for build a copy of collab aside every time a save is being called.

chore: reuse group collab for indexing

---

services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/group/state.rs
services/appflowy-collaborate/src/metrics.rs
services/appflowy-collaborate/src/rt_server.rs

This PR removes `CollabMetricsCalculate` - the same feature is provided by `CollabRealtimeMetrics` which works exactly the same way (`Gauge` internally is equivalent to `AtomcI64`, see the [source code](https://docs.rs/prometheus-client/latest/src/prometheus_client/metrics/gauge.rs.html#45-48)) so we don't need to update it every 2min in a separate task.

chore: remove redundant metrics collector

---

services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/group/state.rs
services/appflowy-collaborate/src/metrics.rs
services/appflowy-collaborate/src/rt_server.rs

Reconnect realtime collab metrics, that were detached from the registry in #770

chore: reconnect realtime metrics

---

libs/database/src/collab/collab_storage.rs
libs/database/src/index/collab_embeddings_ops.rs
services/appflowy-collaborate/src/collab/cache.rs
services/appflowy-collaborate/src/collab/disk_cache.rs
services/appflowy-collaborate/src/collab/queue.rs
services/appflowy-collaborate/src/collab/storage.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/indexer/provider.rs
services/appflowy-collaborate/src/rt_server.rs
src/api/workspace.rs
tests/collab/storage_test.rs

Use CollabStorage to get encode collab instead of query from db directly.

chore: use colla storage instead of select from db directly

---

deploy.env
dev.env

This documents the findings from #537 in both .env templates: smtps (TLS) is mandatory for `APPFLOWY_MAILER_SMTP`.

fix: add doc note for mandatory smtps

---

deploy.env
docker-compose-ci.yml
docker-compose-dev.yml
docker-compose-extras.yml
docker-compose.yml

This commit allows the port to be controlled using environment variables without having to edit the file which can be troublesome as this app is deployed as a git repo.
Additionaly this commit removes the `version` field which is now deprecated (read: https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete)

feat: modernized the docker-compose file

---

Cargo.lock
libs/database-entity/Cargo.toml
libs/database-entity/src/dto.rs
libs/database/src/collab/collab_db_ops.rs
script/client_api_deps_check.sh
services/appflowy-collaborate/src/collab/queue.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/indexer/provider.rs
src/biz/user/user_init.rs
src/biz/workspace/publish_dup.rs
tests/collab/collab_curd_test.rs
tests/collab/storage_test.rs
tests/sql_test/workspace_test.rs

While monitoring the response time of the batch_collab API endpoint, we observed some unexpectedly long-running tasks, even when the payload is very small. we are attempting to resolve it by using spawn_blocking to offload potentially blocking tasks onto a separate thread pool

fix: using spawn_blocking in order to not block the runtime

---

src/biz/collab/publish_outline.rs

Hide space without any published documents, and allow collab that are published in private space to be displayed.

fix: hide space without any published documents

---

Dockerfile
admin_frontend/Dockerfile
admin_frontend/src/config.rs
admin_frontend/src/main.rs

This PR makes some minor changes to support deploying on railway: 
- allows setting the host and port for the admin service via an environment variable. This allows using ipv6 (this was already done for af-cloud)
- exposes container ports for af-cloud and admin via environment variables
Testing: 
- Tested on my own deployments on railway

feat: Support Railway Deployments

---

.sqlx/query-2dda0bc4d9486a49c0af00d8ee4408c970a2ba3533217c130281e7db5a4e3d6b.json
.sqlx/query-d205df7e6a71335bc457f560fa5a941c738cd1f8e7c3369b0b24bb34fbb1c6eb.json
libs/database-entity/src/dto.rs
libs/database/src/file/file_storage.rs
libs/database/src/file/s3_client_impl.rs
libs/database/src/publish.rs
libs/database/src/workspace.rs
src/api/metrics.rs
src/api/workspace.rs
src/application.rs
src/biz/workspace/ops.rs
src/biz/workspace/publish.rs
src/biz/workspace/publish_dup.rs
src/config/config.rs
src/state.rs

This PR will introduce a new trait, PublishedCollabStore, which will handle the different operations for publish collabs. Two different implementation has been introduced: one write and read exclusively from postgres as per status quo, the other will write to both s3 and postgres, and read from s3 with postgres as fallback.

feat: Support s3 as published collab storage

---

libs/app-error/src/lib.rs
libs/client-api/src/http.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
src/biz/collab/publish_outline.rs
tests/workspace/publish.rs
tests/workspace/workspace_folder.rs

Fixes:
- Originally, the default folder view is return if a view cannot be retrieved by id from the Folder struct. The appflowy web frontend might display the wrong result. This PR filter out such views from the output tree instead.
- There are child views which their parent view id attribute does not match the parent view's id. Such case is due to malformed encoded collab and should have been filtered out.
New features:
- A new query parameter named root_view_id, that allows the caller to iterate the folder view from any view, not just the root workspace id. Will be used in the future by the appflowy web frontend.
- Add is_published and layout fields to the FolderView.
- Return error if no valid nodes are found in the folder view tree

feat: add additional fields to FolderView and support different root id

---

libs/client-api/src/http.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
tests/workspace/workspace_folder.rs

Add endpoints to retrieve favorite, trash and recent views belonging to a workspace and the user who send the request.

feat: add retrieve sections endpoints

---

.sqlx/query-84c224af99f654e2e0ba11a411376794855483eedb0c30b1873ed660ca8d10cd.json
libs/client-api/src/http_view.rs
libs/client-api/src/lib.rs
libs/database/src/user.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/workspace/mod.rs
src/biz/workspace/page_view.rs
tests/workspace/mod.rs
tests/workspace/page_view.rs

Add endpoints to support rendering a collab on the web version of Appflowy. The collab for the database rows are included together as part of the response, if the view layout is Grid, Board, or Calendar.
The current number of rows supported by the import CSV function is 1000 rows. Based on test, the performance for retrieving all 1000 rows at once is still acceptable, as long as there are not too many columns.
The yrs doc state is returned directly, as opposed to EncodedCollab.

feat: add endpoint for getting page view collab

---

.sqlx/query-4476f271f4ea8c83428b4178c43ee2894e380a7c3ae3cbc782f438fabc45de8b.json
.sqlx/query-598e731078fc6417039cc16772eb5bc6c74d24c1a8018a981d2175a483dc699c.json
.sqlx/query-6317de690a65f0cb63e2f9d4889fc929f05df7ccfc0b7cb955787d0f88f91c45.json
.sqlx/query-95b1b405028c45c074121110d046f42f8229f150c2384671802ee7c1ef9e376d.json
libs/app-error/src/lib.rs
libs/client-api/src/http_access_request.rs
libs/client-api/src/lib.rs
libs/database-entity/src/dto.rs
libs/database/src/access_request.rs
libs/database/src/lib.rs
libs/database/src/pg_row.rs
libs/shared-entity/src/dto/access_request_dto.rs
libs/shared-entity/src/dto/mod.rs
libs/shared-entity/src/dto/workspace_dto.rs
migrations/20240924045045_access_request.sql
src/api/access_request.rs
src/api/mod.rs
src/application.rs
src/biz/access_request/mod.rs
src/biz/access_request/ops.rs
src/biz/mod.rs
tests/workspace/access_request.rs
tests/workspace/mod.rs

This PR provides the following endpoints:
- POST /api/access-request : for user to submit request to access a view
- GET /api/access-request/{request-id}: for user to retrieve information of an access request. Used for the approval page on AppFlowy Web.
- POST /api/access-request/{request-id}/approve: for workspace owner to add the requester as a member of a workspace
An email should be sent to the workspace owner when a user request for access. This is not implemented yet, will be in another PR.

Endpoints to support page view approval workflow

---

libs/client-api/src/http.rs
libs/shared-entity/Cargo.toml
libs/shared-entity/src/dto/mod.rs
libs/shared-entity/src/dto/server_info_dto.rs
src/api/mod.rs
src/api/server_info.rs
src/application.rs
tests/main.rs
tests/server_info/info.rs
tests/server_info/mod.rs

There are a few scenarios which it will be helpful for a client to be aware of the functionality currently supported by AppFlowy Cloud:
1. A user is using self hosting an older version of AppFlowy Cloud, which does not support some of the newer functionality introduced by the newer client. Having a server info endpoint will allow the client to either provide a fallback, or provide appropriate error message to the user.
2. A user is using an older version of AppFlowy client, which relies on functionality that is already deprecated by AppFlowy Cloud. By checking the features supported by the server, the client can prompt the user to upgrade the client version.

Endpoint for server info

---

assets/mailer_templates/build_production/access_request_approved_notification.html
email_template/config.js
email_template/config.production.js
email_template/src/templates/access_request_approved_notification.html
src/api/access_request.rs
src/biz/access_request/ops.rs
src/mailer.rs

Send an email to notify user that their access request has been approved.

feat: send notification when access request is approved

---

src/api/access_request.rs
src/biz/access_request/ops.rs
tests/workspace/access_request.rs

Returns NotEnoughPermission error when users other than the workspace owner is trying to view an access request. This is so that the web frontend can decide if a user should be able to access the approval landing page.

fix: allowed workspace owner only to view access request

---

Cargo.lock
Cargo.toml
libs/database/src/collab/collab_storage.rs
services/appflowy-collaborate/Cargo.toml
services/appflowy-collaborate/src/collab/storage.rs
services/appflowy-collaborate/src/command.rs
services/appflowy-collaborate/src/rt_server.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs

Currently, there is no options for retrieving encoded collab in batch from the in-memory collab, unlike the fetch single collab counter part.
This is less of a problem for the flutter app, because we do have a websocket client which will eventually sync every collab to the latest, even if the initially fetched data might be outdated.
For AppFlowy Web, however, the changes are pull when the data is refreshed, and there is no websocket client there to keep the state of the collab to the latest. Hence, in cases where the user has a database, changes to the content of the database will not be reflected immediately on the web version of AppFlowy, because the content is fetched via the batch get encoded collab method.
Therefore, an option has been added to the batch get encoded collab method, …

feat: support fetching encoded collab in batch from memory

---

libs/database/src/workspace.rs
src/biz/workspace/ops.rs

Most of the publish related operations have been moved to a separate crate, leaving some duplicates in the original.

chore: remove publish collab related dead code

---

libs/collab-rt-protocol/src/data_validation.rs
libs/database/src/collab/cache.rs
libs/database/src/collab/collab_storage.rs
services/appflowy-collaborate/src/collab/queue.rs
services/appflowy-collaborate/src/collab/storage.rs
services/appflowy-collaborate/src/collab/validator.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/snapshot/snapshot_control.rs
src/api/util.rs
src/api/workspace.rs
tests/collab/collab_curd_test.rs
tests/workspace/import_test.rs

1. use rayon to do decompression and data validation
2. using copy instead of insert one by one to postgres in the background queue

chore: using copy to improve write speed of batch collab api endpoint

---

src/biz/collab/folder_view.rs

Currently, if a view is both a private view, and also in trash, it is still displayed as part of the workspace folder structure.

fix: filter out private view in trash for folder struct

---

src/biz/collab/folder_view.rs

Currently, get_all_private_sections might return views which are not under the private space, under some circumstances. such as when the view is moved from private to public space. To mitigate this issue, we will filter the views based on the space the view belongs to, as opposed to relying on the view attribute itself.

fix: filter private views based on parent space

---

libs/client-api/src/http_collab.rs
libs/database-entity/src/dto.rs
src/api/metrics.rs
src/api/workspace.rs
src/biz/workspace/ops.rs
src/biz/workspace/page_view.rs
src/biz/workspace/publish_dup.rs
src/state.rs
tests/collab/mod.rs
tests/collab/web_edit.rs
tests/workspace/publish.rs

Add API endpoint to receive updates from AppFlowy Web and apply the changes to the collab stored in-memory / on the database. As of now AppFlowy Web does not need to be updated until the browser is refreshed, hence there is no need to send missing updates back to the web client.

feat: support appflowy web editing for document

---

src/api/workspace.rs

Allow access control to be enfored if the middleware is disabled and workspace access control is enabled.

chore: add access control to appflowy web related endpoint

---

deploy.env

Set the password for Postgres separately and ensure that all connection strings related to Postgres share this variable setting.
check service environment variable
```bash
docker compose config {service_name}
```
example: `docker compose config appflowy_cloud`
env setting postgres password to changepassword
```.env
POSTGRES_PASSWORD="changepassword"
...
```
`docker compose config appflowy_cloud` will return
```yaml
name: appflowy-cloud
services:
appflowy_cloud:
build:
context: /Users/thanatosdi/Dev/AppFlowy-Cloud
dockerfile: Dockerfile
args:
FEATURES: ""
environment:
APPFLOWY_ACCESS_CONTROL: "true"
APPFLOWY_AI_SERVER_HOST: ai
APPFLOWY_AI_SERVER_PORT: "5001"
APPFLOWY_DATABASE_MAX_CONNECTIONS: "40"
APPFLOWY_DATABASE_URL: postgres://postgres:changepassword@postgres:5432/postgres …
```

feat: parameterize the postgres password

---

libs/access-control/src/casbin/adapter.rs
libs/access-control/src/metrics.rs

The metric for measuring access control time was described as using seconds as the measurement unit, even though the actual implementation uses milliseconds.

chore: fix misleading metric description and method name for access control metrics

---

libs/client-api/src/http_publish.rs
src/api/workspace.rs

- Wraps the original publish metadata response with `AppResponse` 
- Retains but deprecate the old endpoint `/published/{publish_namespace}/{publish_name}`
- Client Api now uses `/v1/published/{publish_namespace}/{publish_name}`

chore: publish metadata wrapper

---

libs/access-control/src/casbin/access.rs
libs/access-control/src/casbin/collab.rs
libs/access-control/src/casbin/enforcer.rs
libs/access-control/src/casbin/workspace.rs
libs/access-control/src/collab.rs
libs/access-control/src/noops/collab.rs
libs/access-control/src/noops/workspace.rs
libs/access-control/src/workspace.rs
libs/database/src/collab/collab_storage.rs
services/appflowy-collaborate/src/collab/access_control.rs
services/appflowy-collaborate/src/collab/storage.rs
src/api/workspace.rs
src/biz/access_request/ops.rs
src/biz/collab/access_control.rs
src/biz/workspace/access_control.rs

Currently, the access control trait will return true if the subject has access to the object, and false otherwise. This makes it possible to enforce the behavior of the implementation: it is very clear that the app error means unexpected behaviour, and the boolean return value indicate whether the user has access or not.
However, on the caller's end - it became impossible to enforce the error type to return if the user does not have the access. It is very possible for the caller to accidentally return a different error code, which will result in inconsistency. There's also additional handling required for every call, to return permission error if the result is false.
It is possible to enforce the returned error code by having a middleware that will be used by every single endpoints that …

chore: access control interface to return error instead of boolean

---

src/api/search.rs
src/api/workspace.rs

Enable access control for workspace level CRUD, before deprecating the use of middleware.
Ideally, we should use Uuid for the workspace id argument, as most endpoints that requires access control extracts the workspace id from the url path as a Uuid. However, it is difficult to do so now due to the fact that CollabGroup is storing workspace id in the form of string, which makes it more convenient to use String instead of Uuid, for RealtimeAccessControl.

feat: enforce access control on workspace level CRUD

---

.sqlx/query-e2ab2c5d0328f2a0900dfbd9080c0d867526bca0afee9aa4af294fbbebf3db0a.json
libs/database-entity/src/dto.rs
libs/database/src/publish.rs
src/api/template.rs
src/biz/template/ops.rs
tests/workspace/template.rs

Add publish info to list templates endpoint. It is assumed that published info can always be found for a given template/view id.

feat: add publish info to list templates

---

.github/workflows/push_latest_docker.yml

Gotrue image build failed due to wrong docker file path being supplied as parameter.

fix: Fix gotrue image build

---

migrations/20230312043024_user.sql
migrations/20230906101223_workspace.sql
migrations/20230906102652_collab.sql

`authenticated` and `anon` role was needed in the past due to dependency on supabase. Now that we are no longer using supabase, there's no reason why authenticated and anon roles should exists, nor do we need row level security.
For existing users, the script will not make any changes: the roles will still exists, so is row level security. New users, however, will be able to install appflowy cloud without using these extra roles, or forced to used a postgres super user for appflowy cloud.

Remove dependency on anon and authenticated role, disable row level security

---

libs/client-api/src/http.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
tests/workspace/workspace_folder.rs

Added section timestamp to the response for get recent, favorite and trash section endpoints. The response json format will be in the form of:
Favorite sections:
```
{
views: [
{
...all fields in FolderView
favorited_at: <date time>
}
]
}
```
Recent sections:
```
{
views: [
{
...all fields in FolderView
last_viewed_at: <date time>
}
]
}
```
Trash sections:
```
{
views: [
{
...all fields in FolderView
deleted_at: <date time>
}
]
}
```

Add section timestamp for get recent/favorite/trash section endpoints

---

libs/client-api-test/src/test_client.rs
tests/workspace/publish.rs

This PR attempts to fix the duplication test cases that were failing occasionally. Failing tests are not able to be reproduced in my local machine. I suspect that during duplication, it takes a while for the folder collab to be updated, and the next test steps fetches the folder structure right after duplication occurs.
Occasional failing test:
https://github.com/AppFlowy-IO/AppFlowy-Cloud/actions/runs/11493712274/job/31991004609?pr=922
https://github.com/AppFlowy-IO/AppFlowy-Cloud/actions/runs/11495849319/job/31997895457?pr=929

fix: wait for a second after duplication to workspace

---

docker-compose.yml

Minio browser redirect url was wrongly set to localhost.

fix: wrong minio browser redirect url

---

admin_frontend/Dockerfile

Since we are using vendored crate for protobuf compiler in appflowy collab, there is no need to explicitly installed protobuf compiler for admin frontend.
Although, we might still want to move /src to /appflowy_cloud/src so that the dependencies in Cargo.toml in the parent dir doesn't get merged with the Cargo.toml on admin frontend service (which was why protobuf compiler became a dependency, eventhough admin frontend doesn't rely on appflowy collab)

chore: remove protobuf compiler from admin frontend docker image

---

.sqlx/query-12dcf313d0e4c0c0da2569f3326e49e1a78fa54537cb8826a20bef2769d04dd1.json
.sqlx/query-2571550f7e2dd81103960741fecbf886f52f681c44344a814780b01fc06e4c8f.json
libs/app-error/src/lib.rs
libs/database/src/workspace.rs
src/biz/workspace/publish.rs
tests/workspace/publish.rs

- If a collab is already publish under a `view_id` and user tries to publish another `view_id` with same `publish_name` as the previous, an error `PublishNameAlreadyExists = 1050` will be returned.
- If a collab is already published, user cannot change the `publish_name` to one that already exists for the workspace, error `PublishNameAlreadyExists = 1050` will be returned

feat: handle duplicated publish names for a workspace

---

migrations/before/supabase_auth.sh

Database name on the migration script should be based on the postgres db env variable instead of hardcoded to postgres.

fix: parameterized postgres db in migration script

---

libs/client-api/src/http_view.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

Add API to move page to trash folder. The page will be removed from favorite before moving to trash, similar to the desktop app behaviour.

feat: api for moving page to trash

---

libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs
tests/workspace/workspace_folder.rs

Add an optional parameter for create page API, so that the caller can provide the view name.

feat: allow create page API to accept a view name

---

libs/access-control/src/casbin/access.rs
libs/access-control/src/casbin/enforcer.rs

Casbin matcher was changed in https://github.com/AppFlowy-IO/AppFlowy-Cloud/commit/d0c212ff10ecf758764bf209fa91db0f5a769dbf to support collab group. However, doing so seems to negatively impact the performance of the policy evaluation.

fix: revert changes to casbin matcher

---

libs/client-api/src/http_collab.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/ops.rs
tests/workspace/workspace_crud.rs

- Incur lookup for 1 Database Collab
- Fetches only ids of row, so operation is not expensive
- Allows external services to poll this api, using difference in ID to detect if a row was added
- Incur 1 Database collab look up + number for rows looked up
- Transform result into human readable format
- Incur 1 Workspace Database collab lookup + 1 Folder Collab lookup
- Get names based on folder
- Previously, a lookup was for every database
- As a result, there is no need for filtering in the backend

feat: list database row

---

libs/client-api/src/http_view.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

Modify the move to trash API behaviour such that, if a parent is move to trash section, the child doesn't.

fix: remove only parent page when move to trash

---

libs/database-entity/src/dto.rs
libs/database/src/collab/cache.rs
libs/database/src/collab/disk_cache.rs
services/appflowy-collaborate/src/application.rs
services/appflowy-collaborate/src/config.rs
src/application.rs
src/config/config.rs

This PR enables setting up a threshold, by which collabs land in either S3 or Postgres to be an env var `APPFLOWY_COLLAB_S3_THRESHOLD` (defaults to 8000 bytes so that it fits a singe Postgres TOAST page, but not more).

chore: make collab storage switch between s3 and postgres configurable

---

docker/gotrue/Dockerfile
docker/gotrue/start.sh

https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/1034 currently failed the integration test because the test is using the current latest appflowy gotrue image instead of building them. As a workaround, this PR will add the change to the gotrue image, and omit the rest of the changes in 1034. Once a new image has been built we can rerun the test in 1034.

feat: support admin account creation for gotrue image

---

libs/database/src/collab/collab_storage.rs
services/appflowy-collaborate/src/collab/storage.rs
src/api/workspace.rs
src/biz/user/user_init.rs
src/biz/workspace/page_view.rs
src/biz/workspace/publish_dup.rs

1. Rename insert _new_collab_with_transaction to upsert_new_collab_with_transaction , as the operation will update existing collab if found.
2. web-update endpoint should use this method so that both mem and disk cache will be updated.

fix: web update should update both disk and mem cache

---

src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
src/biz/workspace/page_view.rs
tests/workspace/publish.rs

Filter out documents which is not a space from workspace's children.
Some existing tests failed as the documents are created under a workspace as opposed to a space, which has been modified in this PR.

fix: filter non space document from workspace's children

---

services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-worker/src/import_worker/worker.rs

The response from server to the websocket client in handle_sync_step should always have origin = CollabOrigin::Server. instead of the original message origin.

fix: synchronization issue due to incorrect collab origin

---

services/appflowy-collaborate/src/actix_ws/client/rt_client.rs
services/appflowy-collaborate/src/actix_ws/server/rt_actor.rs
services/appflowy-collaborate/src/group/broadcast.rs
services/appflowy-collaborate/src/group/cmd.rs
services/appflowy-collaborate/src/group/group_init.rs
services/appflowy-collaborate/src/group/manager.rs
services/appflowy-collaborate/src/group/persistence.rs
services/appflowy-collaborate/src/group/state.rs
services/appflowy-collaborate/src/rt_server.rs
tests/websocket/actor_test.rs

This PR turns off necessity of using async message handlers in `RealtimeServerActor`. The major reason for using these were:
1. Stopping group requires calling an async `stop` method, which was using an async channel to notify group processing loop that it should be stopped. Now I've changed it to use `CancellationToken` which stops the group when the group instance is dropped. The same goes for group subscribers.
2. `CollabGroup::new` was async because of async lock over collab used inside. However we can pass a `Collab` which isn't wrapped with lock into a group, initialise everything and then wrap it with necessary lock at the end of group constructor.
3. Client message handler was async due to [this](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/ee2ff899a3bb16a13bbabadd88a1625526c …

Remove async awaits from RealtimeServerActor

---

services/appflowy-collaborate/src/collab/cache/collab_cache.rs

This PR fixes an issue when sometimes users got outdated collab state (ie. in web api) because when doing batch collab inserts, we were not updating the redis cache as well, which was returning an outdated values.

fix: update redis cache when inserting collabs in batches

---

Cargo.lock
Cargo.toml
admin_frontend/Cargo.toml
libs/app-error/Cargo.toml
libs/appflowy-ai-client/Cargo.toml
libs/client-websocket/Cargo.toml
libs/database-entity/Cargo.toml
libs/database-entity/src/dto.rs
libs/database/Cargo.toml
libs/infra/Cargo.toml
libs/shared-entity/Cargo.toml
libs/shared-entity/src/dto/chat_dto.rs
script/client_api_deps_check.sh
services/appflowy-collaborate/Cargo.toml
services/appflowy-worker/Cargo.toml
src/domain/user_email.rs

Update validator to version 0.19 in order to pass security audit.
EDITED: reqwest will also need to be updated in order to pass security audit

chore: update validator crate

---

libs/client-api/src/http_view.rs
src/api/metrics.rs
src/api/util.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

API for deleting items from trash permanently. Currently, this API only modifies the workspace folder, as opposed to actually delete the collab from the database. This is consistent with the behavior of the current version of AppFlowy desktop app. We will need to revisit this in the future.
This API is also differ from other page view related APIs, as the updates are written to in-memory Collab Group as opposed to directly to the database. After this PR is merged, we will migrate all the other APIs to follow similar approach.

feat: api for delete items from trash permanently

---

services/appflowy-collaborate/src/group/cmd.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

Refactor the page view API to update the collab group as opposed to writing to database directly.
This PR also includes https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/1087
This also fixes some test case which incorrectly use the mock desktop client instead of the mock web client in order to send web updates.

chore: refactor page view APIs to write to in-memory collab group

---

services/appflowy-collaborate/src/group/cmd.rs

Currently, when handling realtime update via http, the decision of  whether a user should be subscribed to a group is determined by whether the client router exists for the user or not.
This is inconsistent with the web socket client behavior. It is possible, that the client router already exists for a user (eg. when multiple web updates are sent with the same device id header) , but a new subscription is still needed because the user has not yet subscribed to a different group. (eg. user is subscribed to workspace folder changes but not workspace database changes).

fix: incorrect group subscription criteria for http real time user

---

.sqlx/query-794c4ced16801b3e98a62eb44c18c14137dd09b11be73442a7f46b2f938b8445.json
libs/client-api/src/http_chat.rs
libs/database/src/chat/chat_ops.rs
src/api/chat.rs
src/biz/chat/ops.rs
tests/ai_test/chat_test.rs

Currently, question (sent by user) messages in the `chat_message_table` may contain a value in the `reply_message_id` column to reference its answer message. However, answer messages do not have a reference to the question that w as asked. This PR allows for a way to try to find the question to which an answer was made.

chore: find question message from reply message

---

.sqlx/query-35622d4ebede28dd28b613edcf3970ad258286f176ce86e88bd662a602e4ad58.json
.sqlx/query-5cce5f82c0fb9237f724478e2167243bc772c092910f07b8226431a6dd70a7da.json
.sqlx/query-770a4979e137ca08c5ea625259221f9d397a56defb8e498eb92da7b3a8af612b.json
libs/client-api/src/http_quick_note.rs
libs/client-api/src/lib.rs
libs/database-entity/src/dto.rs
libs/database/src/lib.rs
libs/database/src/pg_row.rs
libs/database/src/quick_note.rs
migrations/20241216080018_quick_notes.sql
src/api/workspace.rs
src/biz/workspace/mod.rs
src/biz/workspace/quick_note.rs
tests/workspace/mod.rs
tests/workspace/quick_note.rs

CRUD API for quick notes.
Quick notes will only be used on the appflowy web, and is private to workspace+user. The content of quick note is a json  value provided by the web editor. The exact schema and fields values of this json value is of no concern to the backend, except when it comes to filtering, where the backend needs to return a search result that includes all quick notes with json values where at least one of the value for "insert" field contains the search term. The "insert" field can be nested.

feat: quick note CRUD APIs

---

.sqlx/query-ad216288cbbe83aba35b5d04705ee5964f1da4f3839c4725a6784c13f2245379.json
libs/database/src/index/collab_embeddings_ops.rs
services/appflowy-collaborate/src/indexer/indexer_scheduler.rs

Fix the timeout issue when fetching unindexed collabs. Instead of fetching all unindexed collabs at once, storing them in a stream, and then processing them in bulk, we will fetch and process each unindexed collab one at a time to reduce the load and avoid timeouts

chore: return unindex collab one by one

---

services/appflowy-collaborate/src/indexer/indexer_scheduler.rs
src/api/workspace.rs

There is a stack overflow issue when indexing batch collabs. This PR temporarily disables batch indexing, and I will open a separate PR to fix the underlying issue with batch indexing.

chore: disable batch index

---

libs/database/src/quick_note.rs
tests/workspace/quick_note.rs

Sort quick notes with update time instead of creation time.

fix: sort quick notes by update time

---

deploy.env

`docker-compose.yml` has env variable `ADMIN_FRONTEND_APPFLOWY_CLOUD_URL` set to `${ADMIN_FRONTEND_APPFLOWY_CLOUD_URL:-http://appflowy_cloud:8000}`, though `deploy.env` makes no mention of the variable. In my environment, I needed to change the hostname which would also require changing it in `deploy.env` where it is not mentioned. I suggest adding it with the default value for convenience and consistency (the other two `ADMIN_FRONTEND_...` are included) purposes.

fix: added missing env parameter for ADMIN_FRONTEND_APPFLOWY_CLOUD_URL to deploy.env

---

deploy.env

Postgres host name for GOTRUE_DATABASE_URL is hardcoded as `postgres` , changed it to existing env variable

fix: change postgres host to env variable instead of hard-coded

---

Cargo.lock
libs/collab-stream/Cargo.toml
libs/collab-stream/src/client.rs
libs/collab-stream/src/lib.rs
libs/collab-stream/src/metrics.rs
libs/collab-stream/src/stream_router.rs
libs/collab-stream/tests/collab_stream_test/test_util.rs
services/appflowy-collaborate/src/application.rs
services/appflowy-collaborate/src/state.rs
src/application.rs
src/state.rs

This PR comes with 2 changes:
1. `CollabStreamMetrics` type which allows us to track how many streams are we scheduling to be read at given time:
- `collab_stream_reads_enqueued` is incremented for every stream that has been observed. When the Redis xread returns and stream needs to be rescheduled for the next poll iteration, it also becomes enqueued.
- `collab_stream_reads_dequeued` is incremented for every stream that scheduler returned for xread. These two metrics should be fairly close to each other. If they reads_enqueued grows faster than reads_dequeued it means, that we schedule new stream read requests faster than we can handle them.
2. It fixes the issue when an observer was not correctly dropped and stayed inside of stream router for as long as no new objects where pulled from …

chore: add metrics to redis collab stream

---

Cargo.lock
Cargo.toml
src/api/workspace.rs
src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
src/biz/collab/utils.rs
src/biz/workspace/page_view.rs

In older version of AppFlowy, there's no concept of space. As a result, they can't be rendered in AppFlowy Web easily. In this PR, we will attempt to fix such case based on the following logic:
1. If the view that corresponds to the workspace has children, but none of the children are a valid space, or there is no children at all, then create a new space.
2. If there is at least one children, then all the children directly under the workspace view should be moved under the newly created space.

fix: auto patch workspace folder without space

---

libs/client-api/src/http_publish.rs
libs/client-api/src/http_view.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/ops.rs
src/biz/collab/utils.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

API endpoint for publishing a page to web.

feat: api for publish page to web

---

src/api/search.rs
src/api/workspace.rs
src/biz/collab/folder_view.rs
src/biz/collab/ops.rs
src/biz/search/ops.rs

Private document should not appear when searching the documents through embeddings.

Avoid leaking private document in search endpoint

---

deploy.env

Add additional explanation to avoid start up failure due to special characters in SUPABASE_PASSWORD and POSTGRES_PASSWORD.

chore: add explantion for password for special characters

---

doc/DEPLOYMENT.md
nginx/nginx.conf

This PR updates nginx.conf such that:
1. It's easier to update the proxy pass values for various services, in the event where the user needs to use the same nginx conf for their external nginx.
2. Easier to update allowed cors origin.
3. Only appflowy web is supposed to be on allowed cors origin, there's no reason why 127.0.0.1:8000 to be on allowed origin.

chore: allow nginx conf to be more easily configurable

---

docker-compose.yml

Allow users to optionally specify APPFLOWY_WEB_URL env variable in AppFlowy Cloud, if they have deployed AppFlowy Web.

feat: allow appflowy cloud docker compose setup to optionally enable appflowy web

---

.github/workflows/integration_test.yml
.github/workflows/stress_test.yml
deploy.env

API_EXTERNAL_URL is meant for the external endpoint for gotrue, not appflowy cloud. Not having gotrue suffix will cause SAML integration to fail.

fix: api external url should be for gotrue, not appflowy cloud

---

.sqlx/query-93f6a59171d7cd08d321c777f24255621280fbcf6a2c009afd601eac16c9ba3a.json
libs/client-api/src/http_view.rs
libs/database/src/publish.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

The current endpoint, which the desktop application used to unpublish page (/workspace/{workspace_id}/publish), cannot be used by AppFlowy Web because this endpoint wrongly expects a request body for a delete method. This PR add a different endpoint that adheres to the REST API convention.
The PR also fixed a previously undiscovered bug, where unpublished pages are still considered published.

feat: endpoint for unpublish page

---

libs/workspace-template/src/lib.rs

New workspace should direct the user to the first document under a space, instead of the first space.

fix: new workspace direct user to a page that is not supposed to be viewable

---

deploy.env
doc/DEPLOYMENT.md
docker-compose.yml

MINIO_REDIRECT_URL was set to ${API_EXTERNAL_URL}/minio. This was originally correct, as API_EXTERNAL_URL was wrongly configured to be the deployment's FQDN instead of gotrue external url. But after this bug was fixed, Minio became inaccessible instead, because of the additional gotrue prefix.
This PR will add an additional env variable, FQDN, to address this.

fix: Minio redirect url shouldn't use API_EXTERNAL_URL

---

docker-compose.yml
nginx/nginx.conf

The current Nginx configuration did not add CORS related header to the gotrue endpoint, which cause sign in via AppFlowy Web to fail when using magic link.

fix: add cors for nginx gotrue configuration

---

.github/workflows/integration_test.yml
.sqlx/query-4787139d2189fc33ac25ac07bb9f585f578bde4cd3f75a7da95aa849a25bca9d.json
libs/database/src/pg_row.rs
libs/database/src/publish.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/biz/collab/ops.rs
src/biz/collab/publish_outline.rs

Add additional publish info to publish outline items so that appflowy web does not need to make additional calls to fetch the additional information.

feat: add publish info to publish outline items

---

libs/client-api/src/http_publish.rs
libs/shared-entity/src/dto/publish_dto.rs
src/api/workspace.rs
src/biz/workspace/publish_dup.rs

Previously, there is no need for returning the newly created page id, because there's no requirement to jump to the duplicated page once the API is called.
However, AppFlowy Web will soon have such requirement, hence the root view id of the duplicate view is required in the response now.

feat: add root view id of the created web template to duplicate published page response

---

libs/database/src/user.rs
src/biz/collab/utils.rs
src/biz/workspace/page_view.rs

Detailed error response for get page view so that users and developers can troubleshoot the exact error that happens if a view cannot be displayed on appflowy web.

chore: detailed error response for get page view

---

doc/DEPLOYMENT.md
docker-compose-extras.yml

it easier to use docker-compose-extras

chore: include default services into extras

---

src/application.rs

Currently, if a bucket cannot be created (eg. due to permission issue), AppFlowy Cloud proceed to run as per normal, even if this would lead to issues down the road.

fix: bucket creation failure should result in the server failing, instead of proceeding

---

libs/database/src/user.rs
src/biz/workspace/page_view.rs

There are situations where last editor or document  owner cannot be found, as illustrated in https://github.com/AppFlowy-IO/AppFlowy/issues/7221 . Get page view API should not fail in such case because last editor and document owner information are not strictly required to render the page.

fix: get page view should handle situation where last editor or document owner cannot be found

---

nginx/nginx.conf

Not adding device id to the header may result in CORS failure when AppFlowy Web calls the web-update API.

fix: add device id header to allowed CORS header list to allow web-update API

---

libs/client-api/src/collab_sync/collab_sink.rs
libs/client-api/src/collab_sync/plugin.rs
libs/collab-rt-entity/src/client_message.rs

```rs
fn receive_local_state(
&self,
origin: &CollabOrigin,
object_id: &str,
_event: &Event,
update: &AwarenessUpdate,
) {
let payload = Message::Awareness(update.encode_v1()).encode_v1();
// ...
ClientCollabMessage::new_update_sync(update_sync) <- Here
```
In the previous implementation, the awareness data was associated with the `ClientCollabMessage::new_update_sync`, which caused the awareness update to be merged into the client update.

fix: do not merge awareness sync data info client update sync data

---

docker-compose.yml
docker/gotrue/Dockerfile

The current health check for gotrue image relies on `nc` , which check if port 9999 is listening. However, the fact that the port is listening doesn't mean that the service is ready. We should check the output for http://localhost:9999/health instead.
We will need curl to achieve the above. Once the latest image has been built, we will update the docker compose file to use curl for healthcheck.

chore: add curl for gotrue image for better healthcheck

---

docker-compose.yml

Follow up https://github.com/AppFlowy-IO/AppFlowy-Cloud/pull/1186 . Now that we have `curl` in the latest gotrue docker image, we can use curl for better health check.

chore: use curl for gotrue health check

---

Dockerfile

Currently, we don't have a good way to provide health check for appflowy cloud in docker compose. Adding curl so that we can use curl to call an endpoint on appflowy cloud, to verify if the server is ready to accept requests.

chore: add curl to appflowy cloud image

---

deploy.env
doc/DEPLOYMENT.md
docker-compose.yml

The env variable, `APPFLOWY_WEB_URL` is not actually used by the docker compose file at the moment because the docker compose file use $FQDN directly. `APFFLOWY_WEB_URL` should be used instead, and the default value for the variable should be set to $FQDN instead of localhost:3000.

fix: appflowy web url env var is not used

---

.github/workflows/push_latest_docker.yml

The process of building docker image for arm architecture takes a long time on amd64 based runner takes a long time due to emulation. As github now supports arm runners, we should use a different runner now.

chore: arm runner for arm image building

---

Cargo.lock
libs/access-control/Cargo.toml
libs/access-control/src/act.rs
libs/access-control/src/casbin/access.rs
libs/access-control/src/casbin/adapter.rs
libs/access-control/src/casbin/collab.rs
libs/access-control/src/casbin/enforcer.rs
libs/access-control/src/casbin/workspace.rs
libs/access-control/src/entity.rs
libs/access-control/src/metrics.rs
libs/access-control/src/request.rs
libs/app-error/src/lib.rs
libs/database/src/workspace.rs
src/biz/access_request/ops.rs

In order to make it easier to introduce fine grain access control, the following changes have been made:
1. Business logic to determine access control will now reside solely on WorkspaceAccessControl, CollabAccessControl and RealtimeAccessControl, instead of having some of them on the AFEnforcer.
2. Enforcer now receive the Acts trait directly instead of ActionVariant. This would make it easier for WorkspaceAccessControl and CollabAccessControl to introduce Workspace and Collab specific actions.

chore: simplify access control implementation

---

src/mailer.rs

Address https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/1185 . Based on community feedback, the term 'Actions Required' is commonly associated with spam email as it creates a sense of urgency.

fix: drop 'Actions Required' from notification mail subject

---

libs/client-api/src/http_chat.rs
libs/database/src/chat/chat_ops.rs
libs/shared-entity/src/dto/chat_dto.rs
src/api/chat.rs
src/biz/chat/ops.rs
tests/ai_test/chat_test.rs

Currently, the get chat messages endpoint returns author uid, which is of i64 type,  as one of the fields in the response. By default, serde will serialize i64 as number in json. This is not an issue when the json response is deserialized in the rust client, as the Rust client can deserialize this field without loss in precision.
On the browser, however, there will be lost in precision, which leads to incorrect uid being return to the web frontend. This will cause further problem down stream, when the uid is used as parameter for other request, like retrieving profile information of the author.

fix: chat message endpoint should return user uuid instead of uid

---

libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs

Add an endpoint to get collab as json object. This serves two purposes:
1. Help with development/debugging, when we need to inspect the content of a collab
2. Ability to read collab as json allows more advanced automation opportunity. For example, a developer can use the API to read a document collab, and perform automation/integration based on the content of the document.

feat: api to get collab as json

---

Cargo.lock
Cargo.toml
libs/app-error/src/lib.rs
libs/client-api/src/http_view.rs
libs/shared-entity/src/dto/workspace_dto.rs
libs/workspace-template/src/document/parser.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

API to add block to the end of a document, which can be utilized by appflowy web (ai chat - add message to document) and web clipper.

feat: api to add block to the end of document

---

Cargo.lock
Cargo.toml
libs/client-api/src/http_view.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/collab/database.rs
src/biz/collab/mod.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

feat: api to create database view

---

doc/GUIDE.md

According to [DEPLOYMENT.md](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md),
> [!Note]
> `docker-compose` (with the hyphen) may not be supported. You are advised to use `docker compose` (without hyphen) instead.
However, only GUIDE.md has `docker-compose` command.
This PR updated it.

fix: change `docker-compose` to `docker compose` command

---

Dockerfile
admin_frontend/Dockerfile
docker/gotrue/Dockerfile
docker/web/Dockerfile
services/appflowy-collaborate/Dockerfile
services/appflowy-worker/Dockerfile

Add [`syntax`](https://docs.docker.com/reference/dockerfile/#syntax) parser directive to the first line of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).
To declare the Dockerfile syntax version to use for the build.
If unspecified, [BuildKit](https://docs.docker.com/build/buildkit/) uses a bundled version of the Dockerfile frontend.
Append `# syntax=docker/dockerfile:1` to the top of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).

chore: add `syntax` parser directive to Dockerfile

---

Cargo.lock
libs/collab-stream/Cargo.toml
libs/collab-stream/src/awareness_gossip.rs
libs/collab-stream/src/client.rs
libs/collab-stream/src/error.rs
services/appflowy-collaborate/src/application.rs
services/appflowy-collaborate/src/group/group_init.rs
src/application.rs

This PR changes `AwarenessGossip` implementation to reduce a number of connections created. I suspect that current main implementation creates a 2 redis connections per collab. This one uses only 2 connections total, regardless of number of collabs.

chore: awareness pubsub switch to lightweight version

---

src/biz/workspace/duplicate.rs

We filtered out some of the child views (eg. those in trash) before duplication. We should remove those views from duplication context as well.

fix: ignore views that are not present during duplication

---

email_template/README.md

The ReadMe for email template is currently broken due to missing links. There is also no need to include the Maizzle logo as the underlying tech stack which we use to build the email assets might change any time.

chore: update readme for email template

---

services/appflowy-worker/src/application.rs
src/main.rs
src/telemetry.rs

Log level for different crate can be controlled directly using RUST_LOG, such as RUST_LOG=appflowy_cloud=info,appflowy_collaborate=trace. This should be controlled by env variable rather than hard coded within application.

chore: init env filter by parsing the default env variable

---

libs/client-api/src/http_view.rs
libs/shared-entity/src/dto/workspace_dto.rs
src/api/workspace.rs
src/biz/workspace/page_view.rs
tests/workspace/page_view.rs

AppFlowy Web will use this endpoint to create a folder view, after updating the database collab locally to create a new database view.

feat: add endpoint to create view without collab

---

src/api/workspace.rs

Unwrap has the potential to cause panic for the API to duplicate page.

fix: avoid using unwrap for duplicate page

---

dev.env
docker-compose-dev.yml

1. Prometheus exporter is not working for gotrue in docker compose dev at the moment and delay the start up of gotrue service. Moreover , we are not actually using it.
2. Adding a health check so that gotrue container doesn't start before the database is ready
3. update dev.env.

fix: remove prometheus exporter from docker compose dev, add postgres condition check and update env

---

docker-compose-ci.yml
docker-compose.yml

Admin frontend will crash if gotrue service is not ready.

fix: admin frontend should wait for gotrue service to start

---

services/appflowy-worker/src/main.rs
src/config/config.rs

default to both ipv6 and ipv4 in Appflowy deployments.  Solves #1505

support both ipv4 and ipv6 by default
